import './globals.css'
import Nav from './auth/Nav'
import { Roboto } from '@next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-48 lg:mx-96 bg-slate-100`}>
        {/* @ts-expect-error Server Component */}
        <Nav />
        {children}
      </body>
    </html>
  )
}
